Ran all python code through black, code formater
HTTP-APIs/hydra-openapi-parser pull request #16
Opened 2019-05-19 17:41 UTC by de-sh

Fixes un-formatted code with black

### Checklist
- [x] My branch is up-to-date with upstream/develop branch.
- [x] Everything works and tested for Python 3.5.2 and above.

### Description

The Black code formatter library is a python standard for maintaining readable code bases, I have run the code of the parser through it to make it more readable and PEP8 compliant.

### Change logs
- Code formatted with black

2019-06-03 16:56 UTC, Mec-iS commented on hydra_openapi_parser/openapi_parser.py
> +    path_ = path.split("/")
you should be sure that the rules for the formatter stick to the conventions we established for the codebase. For example: we decide to always use `'` single quotes for strings, except that for dictionaries meant to be dumped into JSON strings and for variables added via f-strings like `f'Some text with a {dict["variable"]}'`

2019-06-03 16:58 UTC, Mec-iS requested changes

2019-06-03 16:58 UTC, Mec-iS commented on hydra_openapi_parser/openapi_parser.py
> +    path_ = path.split("/")
https://www.python.org/dev/peps/pep-0008/#string-quotes

2019-06-03 17:00 UTC, Mec-iS requested changes

2019-06-03 17:00 UTC, Mec-iS commented on samples/hydra_doc_sample.py
> +                    "writeonly": "true",
I don't see the point of adding all these commas.

Please stick to [pep8 package](https://pypi.org/project/pep8/) as a reference libary

2019-06-03 17:01 UTC, Mec-iS commented
See my review. We cannot really change the styling library every time, we have always been using [pep8 package](https://pypi.org/project/pep8/) as far as I remember

2019-06-03 17:16 UTC, de-sh commented
> See my review. We cannot really change the styling library every time, we have always been using pep8 package as far as I remember.

Ok, These were a suggestion based on the output of black, put it up for review, seems like this is not necessary... comments?

2019-06-03 19:42 UTC, chrizandr commented
I agree, we already have PEP8 based code formatting in all other repos. It would make more sense to stick to it than to change the format to something new. I don't potentially see any benefit in switching over to black.

2019-06-08 12:02 UTC, de-sh commented
@chrizandr I thought [python/black](https://github.com/python/black) is provided by the PSF and hence using it would be better. There is no other reasoning and I have since come to think of not using a no compromise code formatter. I believe it's better to close this PR

2019-06-08 12:03 UTC, closed without merging